version: '3.9'
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    networks:
      - crud

  api:
    depends_on:
      - db
    container_name: node_api
    build:
      context: ./fullstack-app.api
    restart: unless-stopped
    command: npm start
    env_file: ./.env
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_DOCKER_PORT
      - JWT_PRIVATE_KEY=$JWT_PRIVATE_KEY
    ports:
      - 3001:3001
    networks:
      - crud

  ui:
    depends_on:
      - api
    container_name: react_ui
    build:
      context: ./fullstack-app.ui
    ports:
      - 3000:80
    networks:
      - crud

networks:
  crud:
    driver: bridge
