version: '3.9'
services:
  db:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
