#Stage 1
FROM node:alpine as builder

EXPOSE 3000

WORKDIR /app

COPY package*.json .

COPY package-json*.lock .

RUN npm install

COPY . .

RUN npm run build

#Stage 2
FROM nginx:1.19.0

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=builder /app/dist .

ENTRYPOINT ["nginx", "-g", "daemon off;"]